In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import tensorflow as tf
import numpy as np

tf.__version__
tf.keras.__version__

'2.0.0'

'2.2.4-tf'

# Tensors
## NumPy

In [3]:
# Create a tensor
# ---------------

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# np.array(object, dtype)
array2d = np.array(matrix, dtype=np.int32)
array2d

# other alternatives:
# np.zeros
zeros = np.zeros(shape=[4, 4], dtype=np.int32)
zeros

# np.ones
ones = np.ones(shape=[4, 4], dtype=np.int32)
ones

# np.zeros_like / np.ones_like
zeros_like = np.zeros_like(array2d)
zeros_like

# np.arange
range_array = np.arange(start=0, stop=10, step=2)
range_array

# random integers over [low, high)
rnd_int = np.random.randint(low=0, high=10, size=3)
rnd_int

# sampling from distribution: np.random
# uniform [0, 1)
rnd_uniform = np.random.rand(3, 3)  # rand(d0, d1, ..., dN)
rnd_uniform

# normal with mean 0 and variance 1
rnd_normal = np.random.randn(3, 3)  # randn(d0, d1, ..., dN)
rnd_normal

# many others (see documentation)
?np.random

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

array([0, 2, 4, 6, 8])

array([4, 7, 3])

array([[0.36637593, 0.36399332, 0.4056505 ],
       [0.78587641, 0.53621304, 0.7511104 ],
       [0.57900098, 0.47443794, 0.37417134]])

array([[-0.47053982, -1.26764234, -0.28235899],
       [-0.66976752, -1.05179899,  0.55977747],
       [-1.26122886,  0.78345457,  1.04482081]])

In [4]:
# Attributes
# ----------

# dtype: type of the elements
print('array.dtype: %s' % array2d.dtype)

# shape: dimensions of the array
print('array.shape: ', array2d.shape)

# ndim: number of dimensions of the array (axis)
print('array.ndim: {}'.format(array2d.ndim))


array.dtype: int32
array.shape:  (3, 3)
array.ndim: 2


## Tensorflow

In [5]:
# Create a tensor
# ---------------

# tf.constant(object, dtype)
tensor2d = tf.constant(matrix, dtype=tf.int32)
tensor2d

# tf.convert_to_tensor(object, dtype)
tensor2d = tf.constant(array2d, dtype=tf.float32)
tensor2d

# other alternatives:
# tf.zeros
zeros = tf.zeros(shape=[4, 4], dtype=tf.int32)
zeros

# tf.ones
ones = tf.ones(shape=[4, 4], dtype=tf.int32)
ones

# tf.zeros_like / tf.ones_like
zeros_like = tf.zeros_like(array2d)
zeros_like

# np.arange
range_array = tf.range(start=0, limit=10, delta=2)
range_array

# tf.random.uniform
rnd_uniform = tf.random.uniform(shape=[5, 5], minval=10, maxval=20)
rnd_uniform

# ?tf.random

# remember you can use convert_to_tensor()
# e.g.
rnd_rayleigh = tf.convert_to_tensor(
    np.random.rayleigh(size=[2, 2]), dtype=tf.float32)
rnd_rayleigh


<tf.Tensor: id=0, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

<tf.Tensor: id=1, shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

<tf.Tensor: id=4, shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

<tf.Tensor: id=7, shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

<tf.Tensor: id=9, shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

<tf.Tensor: id=13, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

<tf.Tensor: id=20, shape=(5, 5), dtype=float32, numpy=
array([[12.788467, 11.67362 , 16.652027, 17.446955, 14.670211],
       [14.656504, 19.428402, 13.687845, 17.99348 , 10.057428],
       [13.953756, 12.422646, 12.629203, 12.047576, 10.158725],
       [14.72044 , 13.86488 , 12.821474, 12.095869, 18.287252],
       [14.942159, 14.421274, 13.791051, 13.874189, 10.207634]],
      dtype=float32)>

<tf.Tensor: id=21, shape=(2, 2), dtype=float32, numpy=
array([[0.8777093 , 0.6526943 ],
       [1.3856369 , 0.57750493]], dtype=float32)>

In [6]:
# Attributes
# ----------

# dtype: type of the elements
print('tensor2d.dtype: %s' % tensor2d.dtype)

# shape: dimensions of the array
print('tensor2d.shape: ', tensor2d.shape)

# ndim: number of dimensions of the array (axis)
print('tensor2d.ndim: {}'.format(tensor2d.ndim))

# device: device placement for tensor
print('tensor2d.device: {}'.format(tensor2d.device))

tensor2d.dtype: <dtype: 'float32'>
tensor2d.shape:  (3, 3)
tensor2d.ndim: 2
tensor2d.device: /job:localhost/replica:0/task:0/device:CPU:0


## Operations on tensors

In [7]:
# Cast: tf.cast(x, dtype)改data type
# -----------------------

tensor2d.dtype
tensor2d = tf.cast(tensor2d, dtype=tf.int32)
tensor2d.dtype

# ?tf.DType
# -----------------------

tf.float32

tf.int32

In [8]:
# Reshape: 
# --------

# tf.reshape(tensor, shape)
tensor1d = tf.range(9)
tensor1d

tensor2d = tf.reshape(tensor1d, shape=[3, 3])
# tensor2d = tf.reshape(tensor1d, shape=[3, -1]) # negative dimension is accepted
tensor2d

flattened = tf.reshape(tensor2d, shape=[-1])# -1 ==全部 end
flattened

# tf.expand_dims(input, axis)扩展 end 位
tensor2d = tf.reshape(tf.range(1, 5), shape=[2, 2])
tensor2d
tensor3d = tf.expand_dims(tensor2d, axis=-1)
# tensor3d = tf.reshape(tensor2d, shape=[2, 2, 1])
tensor3d

# tf.squeeze(input, axis)
tensor2d = tf.squeeze(tensor3d, axis=-1)
# tensor2d = tf.reshape(tensor3d, shape=[2, 2])
tensor2d
# --------

<tf.Tensor: id=26, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

<tf.Tensor: id=28, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

<tf.Tensor: id=30, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

<tf.Tensor: id=36, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

<tf.Tensor: id=38, shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

<tf.Tensor: id=39, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
# Math:
# -----

# +, -, *, / operators (element-wise)
t1 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
t2 = tf.eye(num_rows=3, num_columns=3)
t2
t1+t2 
# tf.add(t1, t2)
t1-t2 
# tf.subtract(t1, t2)
t1*t2 
# tf.multiply(t1, t2)
t1/(t2+1)
# tf.divide(t1, tf.add(t2, 1))

# tf.tensordot(a, b, axes)
t = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)
tf.tensordot(t, t, axes=[[1], [0]]) # matrix multiplication

# -----

<tf.Tensor: id=67, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

<tf.Tensor: id=68, shape=(3, 3), dtype=float32, numpy=
array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]], dtype=float32)>

<tf.Tensor: id=69, shape=(3, 3), dtype=float32, numpy=
array([[0., 2., 3.],
       [4., 4., 6.],
       [7., 8., 8.]], dtype=float32)>

<tf.Tensor: id=70, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]], dtype=float32)>

<tf.Tensor: id=73, shape=(3, 3), dtype=float32, numpy=
array([[0.5, 2. , 3. ],
       [4. , 2.5, 6. ],
       [7. , 8. , 4.5]], dtype=float32)>

<tf.Tensor: id=85, shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [11]:
# Slicing:
# --------

tensor2d = tf.convert_to_tensor(matrix, dtype=tf.float32)
tensor2d

# Pythonic '[]'
# -------------

# Get a single element: tensor[idx1, idx2, ..., idxN]
# e.g. get element '3'
tensor2d[0, 2]
tensor2d[0, -1]
tensor2d[-3, -1]

# Get a slice: tensor[startidx1:endidx1:step1,..., startidxN:endidxN:stepN] (endidx excluded)！！！不包含最后一位
#          |5 6| 
# e.g. get |8 9| sub-tensor
tensor2d[1:3:1, 1:3:1]
tensor2d[1:3, 1:3]
tensor2d[1:, 1:]

# Missing indices are considered complete slices
# e.g. get first row
tensor2d[0, :]

# Negative indices are accepted
tensor2d[0:-1, 0]

# e.g. get first row reversed！！！通过控制step 得到反顺序
tensor2d[0, ::-1]
# -------------

# API
# ---

# tf.slice(input_, begin, size)

#          |5 6| 
# e.g. get |8 9| sub-tensor 确定好初始位置 得到一个subtensor
tf.slice(tensor2d, [1, 1], [2, 2])

# indexing with condition 用numpy
array2d = np.array(matrix, dtype=np.float32)
array2d[np.where(array2d % 2 == 0)]

# tensor2d[tf.where(array2d % 2 == 0)] does not work!
# use tf.gather_nd(params, indices) and tf.where(condition) to find indices
indices = tf.where(tensor2d % 2 == 0)
tf.gather_nd(tensor2d, indices)

# ---

<tf.Tensor: id=86, shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

<tf.Tensor: id=90, shape=(), dtype=float32, numpy=3.0>

<tf.Tensor: id=94, shape=(), dtype=float32, numpy=3.0>

<tf.Tensor: id=98, shape=(), dtype=float32, numpy=3.0>

<tf.Tensor: id=102, shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [8., 9.]], dtype=float32)>

<tf.Tensor: id=106, shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [8., 9.]], dtype=float32)>

<tf.Tensor: id=110, shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [8., 9.]], dtype=float32)>

<tf.Tensor: id=114, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

<tf.Tensor: id=118, shape=(2,), dtype=float32, numpy=array([1., 4.], dtype=float32)>

<tf.Tensor: id=122, shape=(3,), dtype=float32, numpy=array([3., 2., 1.], dtype=float32)>

<tf.Tensor: id=125, shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [8., 9.]], dtype=float32)>

array([2., 4., 6., 8.], dtype=float32)

<tf.Tensor: id=131, shape=(4,), dtype=float32, numpy=array([2., 4., 6., 8.], dtype=float32)>

In [12]:
# Let's play with an image! PIL是python image lab 
# -------------------------

from PIL import Image

img = Image.open('airplane.jpg')
img

ModuleNotFoundError: No module named 'PIL'

In [ ]:
# 👍👍👍Convert image to tensor
rgb_tensor = tf.convert_to_tensor(np.array(img))
# rgb_tensor

gs_tensor = tf.convert_to_tensor(np.array(img.convert('L')))
# gs_tensor

# Change the color of the airplane!
# tf.where again, but tf.where(condition, x, y)
new_t = tf.where(tf.expand_dims(gs_tensor, -1) > 235, [255, 178, 102], rgb_tensor)
new_img = Image.fromarray(new_t.numpy().astype(np.uint8))
new_img


In [ ]:
# Splitting:
# ----------

rgb_tensor.shape

# tf.split(value, num_or_size_splits, axis)
# vertical
output = tf.split(rgb_tensor, 3, axis=0)
output[0].shape
output[1].shape
output[2].shape

# or
top, bottom = tf.split(rgb_tensor, [500, -1], axis=0)
top.shape
bottom.shape

# horizontal
top_left, top_right = tf.split(top, [900, -1], axis=1)
bottom_left, bottom_right = tf.split(bottom, [900, -1], axis=1)

Image.fromarray(top_left.numpy())
Image.fromarray(top_right.numpy())
Image.fromarray(bottom_left.numpy())
Image.fromarray(bottom_right.numpy())

# ----------


In [ ]:
# Stacking:
# ---------

# tf.concat(values, axis)

# horizontally
top = tf.concat([top_left, top_right], axis=1)
bottom = tf.concat([bottom_left, bottom_right], axis=1)

# vertically
restored = tf.concat([top, bottom], axis=0)

Image.fromarray(restored.numpy())

# ---------